# Generated by Django 2.2.5 on 2019-09-22 22:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('network_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('valid_lengths', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='MajorIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='IIN',
            fields=[
                ('iin', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_validator.Issuer')),
            ],
        ),
    ]
